### ISSUE TITLE
Pass TIME_ZONE param on container launch

### ISSUE THREAD

**Issue by ctf-adam** [DataWearsAHood/hasty-paste#8]
[e.g. log](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Fhasty-paste$252Fecs/log-events/app$252Fhasty-paste$252F22c4db8c8b9f4fb49cc3701f45191bb7)

**Comment by DataWearsAHood** [comment]
Done & verified: https://github.com/DataWearsAHood/hasty-paste/blame/28153e6f6a4f0bc06dd3415d1625f1a652baf8c6/container.tf#L77
